export const FETCH_PODCAST_EPISODES = 'app/SideMenu/FETCH_PODCAST_EPISODES';

export const LOAD_PODCAST_EPISODES = 'app/SideMenu/LOAD_PODCAST_EPISODES';

export const FETCH_EPISODE = 'app/SideMenu/FETCH_EPISODE';
