export default [{ type: 'rss 2.0',
  title: 'Building Nexcast - An Inside Look at Growing a Startup Business',
  pubdate: 'Wed, 14 Dec 2016 07:34:30 +0000',
  lastbuilddate: 'Wed, 03 May 2017 20:07:49 +0000',
  generator: 'Libsyn WebEngine 2.0',
  link: 'http://buildingnexcast.com',
  language: 'en',
  copyright: '',
  docs: 'http://buildingnexcast.com',
  managingeditor: 'hi@nexcast.co (hi@nexcast.co)',
  'itunes:summary': 'Building Nexcast chronicles the many ups and downs of working with a team to execute a vision and bring a product to the world. Appropriate to the medium, this product is a podcast app and new platform that aims to make podcasting better for everyone. \n\nThis is not a business podcast or a tech podcast - it is a peek into the lives of struggling entrepreneurs who want to build something that benefits the community. The ultimate goal is to build the “People’s Podcast App” - one that has all the features users want, without ads or a charge to download.\n\nThe app isn\'t even available yet, so the future is uncertain. The first 12 episodes take you on a journey in and around the brutal but sometimes rewarding world of the startup life. Nobody knows where the next 12 episodes will take us, so grab your earbuds and come along for the ride!',
  image:
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t',
    url: 'http://static.libsyn.com/p/assets/c/2/a/d/c2ade2d446381379/buildIt.jpg',
    title: 'Building Nexcast - An Inside Look at Growing a Startup Business',
    link: 'http://buildingnexcast.com' },
  'itunes:author': 'Nexcast',
  'itunes:keywords': 'business,entrepreneurship,nexcast,nextcast,podcast,startup',
  'itunes:category':
  [{ text: 'Business\r\n\t\t\r\n\t', 'itunes:category': 'Careers' },
  { text: 'Technology\r\n\t\t\r\n\t',
    'itunes:category': 'Podcasting' },
  { text: 'Society & Culture\r\n\t\t\r\n\t',
    'itunes:category': 'Personal Journals' }],
  'itunes:image': { href: 'http://static.libsyn.com/p/assets/c/2/a/d/c2ade2d446381379/buildIt.jpg' },
  'itunes:explicit': 'no',
  'itunes:owner':
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t',
    'itunes:name': 'Brian Sanders',
    'itunes:email': 'brian@nexcast.co' },
  description: 'The story of a struggling startup trying to make podcasting better for everyone.',
  'itunes:subtitle': '',
  'atom10:link':
  [{ 'xmlns:atom10': 'http://www.w3.org/2005/Atom',
    rel: 'self',
    type: 'application/rss+xml',
    href: 'http://feeds.feedburner.com/BuildingNexcast/rss' },
  { 'xmlns:atom10': 'http://www.w3.org/2005/Atom',
    rel: 'hub',
    href: 'http://pubsubhubbub.appspot.com/' }],
  'feedburner:info': { uri: 'buildingnexcast/rss' },
  'media:copyright': '',
  'media:thumbnail': { url: 'http://static.libsyn.com/p/assets/c/2/a/d/c2ade2d446381379/buildIt.jpg' },
  'media:keywords': 'business,entrepreneurship,nexcast,nextcast,podcast,startup',
  'media:category':
  [{ scheme: 'http://www.itunes.com/dtds/podcast-1.0.dtd',
    text: 'Business/Careers' },
  { scheme: 'http://www.itunes.com/dtds/podcast-1.0.dtd',
    text: 'Technology/Podcasting' },
  { scheme: 'http://www.itunes.com/dtds/podcast-1.0.dtd',
    text: 'Society & Culture/Personal Journals' }],
  'media:credit': { role: 'author', text: 'Nexcast' },
  'media:rating': 'nonadult',
  'media:description': { type: 'plain' },
  items:
  [{ text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 13 - False Start',
    pubdate: 'Wed, 14 Dec 2016 07:34:30 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/uZaoU-Bvv6s/part-13-false-start',
    'itunes:image': [Object],
    description: '<p>Hi guys and gals! Sorry about disappearing for a hot second, right after we launched our beta... Yeah so about that, as they say here in Los Angeles, we got axed. Well I guess they say that everywhere, but you get the point. In this week\'s episode we dig in to the reason we\'ve been gone and how we almost became reality tv famous. True story. Unfortunately for us, this unfortunate turn of events forced us to rethink our entire codebase and unfortunately slowed us down RIGHT after we started beta testing. Hope you enjoy our unfortunate story!</p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/uZaoU-Bvv6s" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '10:25',
    'itunes:explicit': 'clean',
    'itunes:keywords': '',
    'itunes:subtitle': 'Hi guys and gals! Sorry about disappearing for a hot second, right after we launched our beta... Yeah so about that, as they say here in Los Angeles, we got axed. Well I guess they say that everywhere, but you get the point. In this week\'s episode we...',
    'media:content': [Object],
    'feedburner:origlink': 'http://buildingnexcast.libsyn.com/part-13-false-start' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Intermission: Angel investor and podcast star at 18 - Harry Stebbings',
    pubdate: 'Wed, 02 Nov 2016 05:47:20 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/9RII51ctDtk/',
    'itunes:image': [Object],
    description: '<p><span style="font-size: 12pt;">We\'re back!! We\'ve been hard at work trying to get our private beta out, so apologies for the delay. This week we take another intermission from our story to interview one of the world\'s biggest tech podcasters, who happens to be 19 and lives in the U.K. (neither of those are typos...).</span></p> <p><span style="font-size: 12pt;">Harry Stebbings is nothing short of a podcasting extraordinaire. We got the chance to ask him a few questions about his story and how he built his podcast from basically nothing. Listen in for a fascinating interview with a rare talent and an incredibly interesting podcaster, Mr. Harry Stebbings.</span></p> <p><span style="font-weight: 400; font-size: 12pt;">Check out the site at <a href= "http://BuildingNexcast.com">http://BuildingNexcast.com</a></span></p> <p><span style="font-size: 12pt;">Get early access to the app by adding your email to <a href= "http://nexcast.co">http://nexcast.co</a></span></p> <p><span style="font-weight: 400; font-size: 12pt;">Let us know your feedback and suggestions on Twitter <a href= "http://twitter.com/buildingnexcast">@buildingnexcast</a></span></p> <p><span style="font-size: 12pt;">Or just email us at <a href= "mailto:hi@nexcast.co">hi@nexcast.co</a></span></p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/9RII51ctDtk" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '34:28',
    'itunes:explicit': 'clean',
    'itunes:keywords': '',
    'itunes:subtitle': 'We\'re back!! We\'ve been hard at work trying to get our private beta out, so apologies for the delay. This week we take another intermission from our story to interview one of the world\'s biggest tech podcasters, who happens to be 19 and lives in the...',
    'media:content': [Object],
    'feedburner:origlink': 'http://www.buildingnexcast.com' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 12 - Full Speed Ahead',
    pubdate: 'Fri, 07 Oct 2016 05:31:42 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/YDePT3D78hc/part-12-full-speed-ahead',
    'itunes:image': [Object],
    description: '<p><span style="font-weight: 400; font-size: 12pt;">We see what happened in the lost weeks without a mobile developer and check in with our new pal Taku. We used to be moving like a glacier, but now we’re on train full speed ahead to beta town.</span></p> <p><span style="font-weight: 400; font-size: 12pt;">Check out the site at <a href= "http://BuildingNexcast.com">http://BuildingNexcast.com</a></span></p> <p><span style="font-size: 12pt;"><span style= "font-weight: 400;">Get early access to the app by adding your email to </span><a href="http://nexcast.co"><span style= "font-weight: 400;">http://nexcast.co</span></a></span></p> <p><span style="font-weight: 400; font-size: 12pt;">Let us know your feedback and suggestions on Twitter <a href= "http://twitter.com/buildingnexcast">@buildingnexcast</a></span></p> <p><span style="font-size: 12pt;"><span style= "font-weight: 400;">Or just email us at </span><a href= "mailto:hi@nexcast.co"><span style= "font-weight: 400;">hi@nexcast.co</span></a></span></p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/YDePT3D78hc" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '13:42',
    'itunes:explicit': 'clean',
    'itunes:keywords': '',
    'itunes:subtitle': 'We see what happened in the lost weeks without a mobile developer and check in with our new pal Taku. We used to be moving like a glacier, but now we’re on train full speed ahead to beta town. Check out the site at http://BuildingNexcast.com Get...',
    'media:content': [Object],
    'feedburner:origlink': 'http://buildingnexcast.libsyn.com/part-12-full-speed-ahead' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 11 - Equity Wars Continue',
    pubdate: 'Fri, 30 Sep 2016 04:06:13 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/zfVgRA6pyy4/part-11-equity-wars-continue',
    'itunes:image': [Object],
    description: '<p><span style="font-weight: 400;">I blow in a call to my friend who made a deal with Mark Cuban on Shark Tank to get some advice on how to sort this equity split out. Then it was time to have the dreaded follow up with Troy. We then have some catastrophic news that we somehow take in stride. </span></p> <p><span style="font-weight: 400;">Check out the site http://BuildingNexcast.com</span></p> <p>Get early access to the app by adding your email to http://nexcast.co</p> <p>Let us know your feedback and suggestions on Twitter @buildingnexcast</p> <p>Or just email us at hi@nexcast.co</p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/zfVgRA6pyy4" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '22:42',
    'itunes:explicit': 'yes',
    'itunes:keywords': '',
    'itunes:subtitle': 'I blow in a call to my friend who made a deal with Mark Cuban on Shark Tank to get some advice on how to sort this equity split out. Then it was time to have the dreaded follow up with Troy. We then have some catastrophic news that we somehow take in...',
    'media:content': [Object],
    'feedburner:origlink': 'http://buildingnexcast.libsyn.com/part-11-equity-wars-continue' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 10 - Equity Wars',
    pubdate: 'Fri, 23 Sep 2016 02:23:07 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/OAUbvNhd6lE/',
    'itunes:image': [Object],
    description: '<p>Splitting up something that’s worth nothing has never been harder.</p> <p>We take some advice from a Stanford class called How to Start a Startup on how to best divide ownership of our company that currently has no real value. The potential of it being worth millions causes a lot of debate. It seems like Farhan doesn’t think Troy should have equal ownership because he doesn\'t know exactly what he is contributing.</p> <p>I talk to everyone individually and then we try to hammer it out as a group. Marife makes a return and plays therapist.</p> <p><span style="font-weight: 400;">Check out the site at</span> <a href="http://BuildingNexcast.com"><span style= "font-weight: 400;">http://BuildingNexcast.com</span></a></p> <p><span style="font-weight: 400;">Get early access to the app by adding your email to</span> <a href= "http://nexcast.co/"><span style= "font-weight: 400;">http://nexcast.co</span></a></p> <p><span style="font-weight: 400;">Let us know your feedback and suggestions on Twitter</span> <a href= "http://twitter.com/buildingnexcast"><span style= "font-weight: 400;">@buildingnexcast</span></a></p> <p><span style="font-weight: 400;">Or just email us at</span> <a href="mailto:hi@nexcast.co"><span style= "font-weight: 400;">hi@nexcast.co</span></a></p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/OAUbvNhd6lE" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '31:01',
    'itunes:explicit': 'clean',
    'itunes:keywords': '',
    'itunes:subtitle': 'Splitting up something that’s worth nothing has never been harder. We take some advice from a Stanford class called How to Start a Startup on how to best divide ownership of our company that currently has no real value. The potential of it being...',
    'media:content': [Object],
    'feedburner:origlink': 'http://buildingnexcast.com/' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 9 - Form the Team / Fend off the Trolls',
    pubdate: 'Thu, 08 Sep 2016 06:19:23 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/heRT0Pv72bY/part-9-form-the-team-fend-of-the-trolls',
    'itunes:image': [Object],
    description: '<p><span style="font-weight: 400;">We have to make a couple big decisions as things start falling into place for our team. We have gotten a lot of positive feedback on bringing discussion threads into our app, a feature that we have been planning all along. Engaging with podcasts hosts and other listeners seems great - we just have to fend off the trolls.</span></p> <p><span style="font-weight: 400;">Check out the site at</span> <a href="http://BuildingNexcast.com"><span style= "font-weight: 400;">http://BuildingNexcast.com</span></a></p> <p><span style="font-weight: 400;">Get early access to the app by adding your email to</span> <a href= "http://nexcast.co/"><span style= "font-weight: 400;">http://nexcast.co</span></a></p> <p><span style="font-weight: 400;">Let us know your feedback and suggestions on Twitter</span> <a href= "http://twitter.com/buildingnexcast"><span style= "font-weight: 400;">@buildingnexcast</span></a></p> <p><span style="font-weight: 400;">Or just email us at</span> <a href="mailto:hi@nexcast.co"><span style= "font-weight: 400;">hi@nexcast.co</span></a></p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/heRT0Pv72bY" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '16:20',
    'itunes:explicit': 'clean',
    'itunes:keywords': '',
    'itunes:subtitle': 'We have to make a couple big decisions as things start falling into place for our team. We have gotten a lot of positive feedback on bringing discussion threads into our app, a feature that we have been planning all along. Engaging with podcasts hosts...',
    'media:content': [Object],
    'feedburner:origlink': 'http://buildingnexcast.libsyn.com/part-9-form-the-team-fend-of-the-trolls' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 8 - The Filipino Teen Gamer Gang Predicament',
    pubdate: 'Wed, 31 Aug 2016 06:13:36 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/9RII51ctDtk/',
    'itunes:image': [Object],
    description: '<p><span style="font-size: 12pt;">Our journey thus far has been full of surprises, but this we couldn\'t make up if we tried. In this week\'s episode we find ourselves on the other end of the negotiating table with a gang of teenaged gamers from the Philippines. They\'ve got our Twitter handle, we need to convince them to give it to us. We get advice from someone who has been in this situation before, but these teen gamers won\'t be easily convinced...</span></p> <p><span style="font-size: 12pt;">Special thanks to TechCrunch "journalisting" extraordinaire <a href= "https://twitter.com/Haje">@Haje</a> Jan Kamps. Check him out on TC, <a href="http://haje.strikingly.com">here</a> and on <a href="https://medium.com/@haje">medium</a>.</span></p> <p><span style="font-size: 12pt;"><span style= "font-weight: 400;">Get early access to the app by adding your email to </span><a href="http://nexcast.co"><span style= "font-weight: 400;">http://nexcast.co</span></a></span></p> <p><span style="font-weight: 400; font-size: 12pt;">Let us know your feedback and suggestions on Twitter <a href= "http://twitter.com/buildingnexcast">@buildingnexcast</a></span></p> <p><span style="font-size: 12pt;"><span style= "font-weight: 400;">Or just email us at </span><a href= "mailto:hi@nexcast.co"><span style= "font-weight: 400;">hi@nexcast.co</span></a></span></p> <p> </p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/9RII51ctDtk" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '34:11',
    'itunes:explicit': 'clean',
    'itunes:keywords': '',
    'itunes:subtitle': 'Our journey thus far has been full of surprises, but this we couldn\'t make up if we tried. In this week\'s episode we find ourselves on the other end of the negotiating table with a gang of teenaged gamers from the Philippines. They\'ve got our Twitter...',
    'media:content': [Object],
    'feedburner:origlink': 'http://www.buildingnexcast.com' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 7 - Playing CTO Tinder',
    pubdate: 'Tue, 23 Aug 2016 06:18:44 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/9RII51ctDtk/',
    'itunes:image': [Object],
    description: '<p><span style="font-size: 12pt;">Not quite as easy as finding a date - we explore the CTO matching services available to non-technical guys like us. We get swindled, have a few laughs, and surprise, surprise, discover that the dating app comparison isn\'t too far off. Will we ever get lucky again? Tune in to find out...</span></p> <p><span style="font-size: medium;">Check out the site at <a href= "http://BuildingNexcast.com">http://BuildingNexcast.com</a></span></p> <p><span style="font-weight: 400;">Get early access to the app by adding your email to </span><a href= "http://nexcast.co"><span style= "font-weight: 400;">http://nexcast.co</span></a></p> <p><span style="font-weight: 400; font-size: 12pt;">Let us know your feedback and suggestions on Twitter <a href= "http://twitter.com/buildingnexcast">@buildingnexcast</a></span></p> <p><span style="font-size: 12pt;"><span style= "font-weight: 400;">Or just email us at </span><a href= "mailto:hi@nexcast.co"><span style= "font-weight: 400;">hi@nexcast.co</span></a></span></p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/9RII51ctDtk" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '15:49',
    'itunes:explicit': 'clean',
    'itunes:keywords': '',
    'itunes:subtitle': 'Not quite as easy as finding a date - we explore the CTO matching services available to non-technical guys like us. We get swindled, have a few laughs, and surprise, surprise, discover that the dating app comparison isn\'t too far off. Will we...',
    'media:content': [Object],
    'feedburner:origlink': 'http://www.buildingnexcast.com' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Intermission: How To Spin A Story',
    pubdate: 'Tue, 16 Aug 2016 02:54:17 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/9RII51ctDtk/',
    'itunes:image': [Object],
    description: '<p><span style="font-size: 12pt;">We\'re taking a hot second to try something new. As you may recall, Part 1 of this epic journey got started in Silicon Valley, where Brian pitched the company for the first time ever at Blab. There were both highs and lows, good points and not so good points, but we ultimately decided to highlight the rough parts of that experience to showcase the realities of pitching a startup. You know, to keep it real real.</span></p> <p><span style="font-size: 12pt;">Well in today\'s episode, we explore the power of framing and interpretation as we present the same episode in a new and positive light. With a bunch of unreleased recordings from that trip, we tell the story that we originally decided not to tell. The good stuff. And with everything that we\'ve endured so far, we figured some positive energy is a bit overdue.</span></p> <p><span style="font-size: 12pt;"><span style= "font-weight: 400;">Get early access to the app by adding your email to </span><a href="http://nexcast.co"><span style= "font-weight: 400;">http://nexcast.co</span></a></span></p> <p><span style="font-weight: 400; font-size: 12pt;">Let us know your feedback and suggestions on Twitter <a href= "http://twitter.com/buildingnexcast">@buildingnexcast</a></span></p> <p><span style="font-size: 12pt;"><span style= "font-weight: 400;">Or just email us at </span><a href= "mailto:hi@nexcast.co"><span style= "font-weight: 400;">hi@nexcast.co</span></a></span></p> <h5> </h5><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/9RII51ctDtk" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '11:51',
    'itunes:explicit': 'clean',
    'itunes:keywords': '',
    'itunes:subtitle': 'We\'re taking a hot second to try something new. As you may recall, Part 1 of this epic journey got started in Silicon Valley, where Brian pitched the company for the first time ever at Blab. There were both highs and lows, good points and not so good...',
    'media:content': [Object],
    'feedburner:origlink': 'http://www.buildingnexcast.com' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 6 - What\'s Up With Podcasts',
    pubdate: 'Tue, 09 Aug 2016 06:22:45 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/9RII51ctDtk/',
    'itunes:image': [Object],
    description: '<p><span style="font-size: 12pt;">We ask a bunch of random people what they think of podcasting and get some surprising answers...</span></p> <p><span style="font-size: 12pt;">The one thing that\'s clear is that podcasting can be different things to different people. And that podcasting needs all the support it can get to break out into the mainstream.</span></p> <p> </p> <p><span style="font-size: 12pt;">To learn more and see all the extra content please go to <a href= "http://buildingnexcast.com">http://buildingnexcast.com</a></span></p> <p><span style="font-size: 12pt;">Get early access to the app by adding your email to <a href= "http://nexcast.co/">http://nexcast.co</a></span></p> <p><span style="font-size: 12pt;">Let us know your feedback and suggestions on Twitter <a href= "http://twitter.com/buildingnexcast">http://twitter.com/buildingnexcast</a></span><br />  <span style="font-size: 12pt;"><br /> Or just email us at <a href= "mailto:hi@nexcast.co">hi@nexcast.co</a></span></p> <p> </p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/9RII51ctDtk" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '30:17',
    'itunes:explicit': 'yes',
    'itunes:keywords': '',
    'itunes:subtitle': 'We ask a bunch of random people what they think of podcasting and get some surprising answers... The one thing that\'s clear is that podcasting can be different things to different people. And that podcasting needs all the support it can get to break...',
    'media:content': [Object],
    'feedburner:origlink': 'http://www.buildingnexcast.com' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 5 - A Long Road Ahead',
    pubdate: 'Tue, 02 Aug 2016 05:19:26 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/9RII51ctDtk/',
    'itunes:image': [Object],
    description: '<p><span style="font-size: 12pt;">There are no sure things when you\'re bootstrapping a startup. We learn that lesson the hard way when we lose a very important member of the team.</span></p> <p><span style="font-size: 12pt;">At this point, our chances of success look pretty grim. I\'m going to have to dig deep to figure out a way out of this mess. Fortunately, I get some good advice from an old friend, Ethan, who always seems to be working with awesome startups. Maybe talking to a good developer will help us find a good developer..?</span></p> <p><span style="font-size: 12pt;">At the end of the day, I have to take responsibility for our team. I learn what it means to dig deep when there doesn\'t seem to be a clear answer ahead.</span></p> <p> </p> <p><span style="font-size: 12pt;">To learn more and see all the extra content please go to <a href= "http://buildingnexcast.com">http://buildingnexcast.com</a></span></p> <p><span style="font-size: 12pt;">Get early access to the app by adding your email to <a href= "http://nexcast.co/">http://nexcast.co</a></span></p> <p><span style="font-size: 12pt;">Let us know your feedback and suggestions on Twitter <a href= "http://twitter.com/buildingnexcast">http://twitter.com/buildingnexcast</a></span><br />  <span style="font-size: 12pt;"><br /> Or just email us at <a href= "mailto:hi@nexcast.co">hi@nexcast.co</a></span></p> <p><span style="font-size: 12pt;"> </span></p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/9RII51ctDtk" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '20:22',
    'itunes:explicit': 'yes',
    'itunes:keywords': '',
    'itunes:subtitle': 'There are no sure things when you\'re bootstrapping a startup. We learn that lesson the hard way when we lose a very important member of the team. At this point, our chances of success look pretty grim. I\'m going to have to dig deep to figure out a way...',
    'media:content': [Object],
    'feedburner:origlink': 'http://www.buildingnexcast.com' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 4 - Community',
    pubdate: 'Tue, 26 Jul 2016 05:39:52 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/9RII51ctDtk/',
    'itunes:image': [Object],
    description: '<p><span style="font-size: 12pt;">Telling your own story can be hard. Making a good podcast about that story is even harder. I get some great advice from some friendly folks as I look at the tech and podcast communities and learn what makes them special.</span></p> <p><span style="font-size: 12pt;">Our podcast journey began in a Slack community called Maker Hunt where people from the <a href= "http://producthunt.com">http://producthunt.com</a> community gather to chat, network, and help each other out. I talk to the creator of this cool corner of the internet Eric Willis. He tells me how he first got connected with Product Hunt and became the community manager there.</span></p> <p><span style="font-size: medium;">I then talk to Josh Muccio who is the host and producer of the podcast version of Shark Tank called The Pitch</span> <a style="font-size: 12pt;" href= "http://thepitch.fm">http://thepitch.fm</a>. <span style= "font-size: 12pt;">He gives me a reality check and gets me to take this whole podcasting thing a lot more seriously.</span></p> <p><span style="font-size: 12pt;">He introduces me to The Intern podcast <a href= "http://theintern.fm">http://theintern.fm</a> which tells the personal tale of Allison Behringer as she begins a new tech job in New York city. Once again I get hit with the realities of telling a story in this medium.</span></p> <p><span style="font-size: 12pt;">The tech community turns out to be very unique and people are surprisingly giving of their time.</span></p> <p><span style="font-size: 12pt;">We also get an interesting email from our developer, Anthony. You’re going to want to stay tuned for what’s next...</span></p> <p> </p> <p><span style="font-size: 12pt;">To learn more and see all the extra content please go to <a href= "http://buildingnexcast.com">http://buildingnexcast.com</a></span></p> <p><span style="font-size: 12pt;">Get early access to the app by adding your email to <a href= "http://nexcast.co/">http://nexcast.co</a></span></p> <p><span style="font-size: 12pt;">Let us know your feedback and suggestions on Twitter <a href= "http://twitter.com/buildingnexcast">http://twitter.com/buildingnexcast</a></span><br />  <span style="font-size: 12pt;"><br /> Or just email us at <a href= "mailto:hi@nexcast.co">hi@nexcast.co</a></span></p> <p><span style="font-size: 12pt;"> </span></p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/9RII51ctDtk" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '24:29',
    'itunes:explicit': 'clean',
    'itunes:keywords': '',
    'itunes:subtitle': 'Telling your own story can be hard. Making a good podcast about that story is even harder. I get some great advice from some friendly folks as I look at the tech and podcast communities and learn what makes them special. Our podcast journey began in a...',
    'media:content': [Object],
    'feedburner:origlink': 'http://www.buildingnexcast.com' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 3 - Keeping Afloat',
    pubdate: 'Tue, 19 Jul 2016 05:55:08 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/9RII51ctDtk/',
    'itunes:image': [Object],
    description: '<p><span style="font-size: 12pt;">Startup life ain\'t easy...</span></p> <p><span style="font-size: 12pt;">No more prancing Pikachu and gleeful little gumdrops in this episode. Things start to get serious when we start falling behind...</span></p> <p> </p> <p><span style="font-size: 12pt;">To learn more and see all the extra content please go to <a href= "http://buildingnexcast.com">http://buildingnexcast.com</a></span></p> <p><span style="font-size: 12pt;">Get early access to the app by adding your email to <a href= "http://nexcast.co/">http://nexcast.co</a></span></p> <p><span style="font-size: 12pt;">Let us know your feedback and suggestions on Twitter <a href= "http://twitter.com/buildingnexcast">http://twitter.com/buildingnexcast</a></span><br />  <span style="font-size: 12pt;"><br /> Or just email us at <a href= "mailto:hi@nexcast.co">hi@nexcast.co</a></span></p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/9RII51ctDtk" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '19:33',
    'itunes:explicit': 'clean',
    'itunes:keywords': '',
    'itunes:subtitle': 'Startup life ain\'t easy... No more prancing Pikachu and gleeful little gumdrops in this episode. Things start to get serious when we start falling behind...   To learn more and see all the extra content please go...',
    'media:content': [Object],
    'feedburner:origlink': 'http://www.buildingnexcast.com' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 2 - How It Began',
    pubdate: 'Tue, 12 Jul 2016 06:35:34 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/9RII51ctDtk/',
    'itunes:image': [Object],
    description: '<p><span style="font-size: 12pt;">“So you spent the first few years trying to pitch this idea to podcast celebrities, trying to get a business model and totally get ignored. Then you bail on a startup that you’d sunk a year into and about 10 grand on. Then you magically built this team, one person off of a reddit thread, and the other by doing a bait-n-switch on a legitimate programmer who just happened to have the exact skill set you were looking for?”</span></p> <p><span style="font-size: 12pt;">That recap from Marife says it all...</span></p> <p><span style="font-size: 12pt;">Next we listen in to how we named our podcast in one of our rare team recordings. This may seem like things are going well, but everything isn\'t cotton candy and smiling baby Pokemon in the near future...</span></p> <p><span style="font-size: 12pt;">To learn more and see all the extra content please go to <a href= "http://buildingnexcast.com">http://buildingnexcast.com</a></span></p> <p><span style="font-size: 12pt;">Get early access to the app by adding your email to <a href= "http://nexcast.co/">http://nexcast.co</a></span></p> <p><span style="font-size: 12pt;">Let us know your feedback and suggestions on Twitter <a href= "http://twitter.com/buildingnexcast">http://twitter.com/buildingnexcast</a></span><br />  <span style="font-size: 12pt;"><br /> Or just email us at <a href= "mailto:hi@nexcast.co">hi@nexcast.co</a></span></p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/9RII51ctDtk" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '25:43',
    'itunes:explicit': 'clean',
    'itunes:keywords': '',
    'itunes:subtitle': '“So you spent the first few years trying to pitch this idea to podcast celebrities, trying to get a business model and totally get ignored. Then you bail on a startup that you’d sunk a year into and about 10 grand on. Then you magically built this...',
    'media:content': [Object],
    'feedburner:origlink': 'http://www.buildingnexcast.com' },
  { text: '\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\t\t',
    title: 'Part 1 - Schooled by Silicon Valley',
    pubdate: 'Wed, 29 Jun 2016 00:31:32 +0000',
    guid: [Object],
    link: 'http://feedproxy.google.com/~r/BuildingNexcast/rss/~3/9RII51ctDtk/',
    'itunes:image': [Object],
    description: '<p><span style="font-size: 12pt;">Part 1 of the epic journey in building the podcast app and platform, Nexcast, begins with a trip to Silicon Valley. Brian Sanders, the CEO and host of the show, travels to San Francisco to pitch his company for the first time ever. The pressure of this challenging start is heightened by visiting the headquarters of two of the biggest tech companies in the world, Apple and Facebook, and seeing what the team is up against. </span></p> <p><span style="font-size: 12pt;">To learn more and see all the extra content please go to <a href= "http://buildingnexcast.com">http://buildingnexcast.com</a></span></p> <p><span style="font-size: 12pt;">Get early access to the app by adding your email to <a href= "http://nexcast.co/">http://nexcast.co</a></span></p> <p><span style="font-size: 12pt;">Let us know your feedback and suggestions on Twitter <a href= "http://twitter.com/buildingnexcast">http://twitter.com/buildingnexcast</a></span><br />  <span style="font-size: 12pt;"><br /> Or just email us at <a href= "mailto:hi@nexcast.co">hi@nexcast.co</a></span></p><img src="http://feeds.feedburner.com/~r/BuildingNexcast/rss/~4/9RII51ctDtk" height="1" width="1" alt=""/>',
    enclosure: [Object],
    'itunes:duration': '34:01',
    'itunes:explicit': 'clean',
    'itunes:keywords': '',
    'itunes:subtitle': 'Part 1 of the epic journey in building the podcast app and platform, Nexcast, begins with a trip to Silicon Valley. Brian Sanders, the CEO and host of the show, travels to San Francisco to pitch his company for the first time ever. The pressure of...',
    'media:content': [Object],
    'feedburner:origlink': 'http://www.buildingnexcast.com' }] },

{ type: 'rss 2.0',
  title: 'Undiscovered',
  description: 'Undiscovered is a podcast about how science really happens. It\'s about all the stuff that gets left out of journal articles – the left turns, false starts, harebrained ideas, and lucky breaks that go into scientific research. It’s scientists telling the story of how they discovered something.\r\n \r\nMost science shows focus on scientific findings – this new thing we know now, that we didn’t know before. But sometimes, the story of HOW the heck scientists figured this new thing out is as compelling – sometimes more! – than the discovery. There are some experiments that are also great stories. Undiscovered is a podcast about those stories.\r\n',
  link: 'http://www.undiscoveredpodcast.org/',
  language: 'en-us',
  copyright: '© 2017 Science Friday',
  generator: 'Drupal 7',
  'itunes:summary': 'Undiscovered is a podcast about how science really happens. It\'s about all the stuff that gets left out of journal articles – the left turns, false starts, harebrained ideas, and lucky breaks that go into scientific research. It’s scientists telling the story of how they discovered something.\r\n \r\nMost science shows focus on scientific findings – this new thing we know now, that we didn’t know before. But sometimes, the story of HOW the heck scientists figured this new thing out is as compelling – sometimes more! – than the discovery. There are some experiments that are also great stories. Undiscovered is a podcast about those stories.\r\n',
  'itunes:category': 'Science & Medicine',
  'itunes:image': { href: 'https://cdn1.pri.org/sites/default/files/Undiscovered_AlbumArt_3000.png' },
  'itunes:author': 'Science Friday',
  'itunes:explicit': 'no',
  'itunes:owner': { text: ' \r\n', 'itunes:email': 'digitalmedia@pri.org' },
  'atom10:link':
  [{ 'xmlns:atom10': 'http://www.w3.org/2005/Atom',
    rel: 'self',
    type: 'application/rss+xml',
    href: 'http://feeds.feedburner.com/pri/undiscovered' },
  { 'xmlns:atom10': 'http://www.w3.org/2005/Atom',
    rel: 'hub',
    href: 'http://pubsubhubbub.appspot.com/' }],
  'feedburner:info': { uri: 'pri/undiscovered' },
  items:
  [{ text: ' \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n',
    title: 'Boss Hua and the Black Box',
    link: 'http://feedproxy.google.com/~r/pri/undiscovered/~3/8jSkGqYixzE/boss-hua-and-black-box',
    description: 'A team of social scientists stumbles onto a cache of censored Chinese social media posts—and decides to find out what the Chinese government wants wiped from the internet.',
    guid: [Object],
    pubdate: 'Tue, 09 May 2017 00:00:00 -0400',
    source: [Object],
    'itunes:subtitle': 'A team of social scientists stumbles onto a cache of censored Chinese social media posts—and decides to find out what the Chinese government wants wiped from the internet.',
    'itunes:summary': '<p>On China’s most influential microblogging platform, a watch aficionado named Boss Hua accuses a government official of corruption. But, his posts aren’t censored. So what disappears into the black box of Chinese censorship...and what stays online? A team of social scientists cracked this question—by mistake—with big data.</p>\r\n',
    'itunes:duration': '37:14',
    'feedburner:origlink': 'https://www.pri.org/programs/undiscovered/boss-hua-and-black-box',
    enclosure: [Object],
    'feedburner:origenclosurelink': 'https://www.podtrac.com/pts/redirect.mp3/cdn.pri.org/sites/default/files/undiscovered/episode-audio/undiscovered-ep1-boss-hua-and-black-box.mp3' },
  { text: ' \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n',
    title: 'Hi! We are Undiscovered.',
    link: 'http://feedproxy.google.com/~r/pri/undiscovered/~3/AgelS6z-_gk/hi-we-are-undiscovered',
    description: 'We\'re a podcast about the left turns, false starts, and lucky breaks that move science forward. ',
    guid: [Object],
    pubdate: 'Tue, 02 May 2017 00:00:00 -0400',
    source: [Object],
    'itunes:subtitle': 'We\'re a podcast about the left turns, false starts, and lucky breaks that move science forward. ',
    'itunes:summary': '<p>We\'re a podcast about the left turns, false starts, and lucky breaks that move science forward. We\'re a new podcast from Science Friday, and we premier Tuesday, May 9.</p>\r\n',
    'feedburner:origlink': 'https://www.pri.org/programs/undiscovered/hi-we-are-undiscovered',
    enclosure: [Object],
    'feedburner:origenclosurelink': 'https://www.podtrac.com/pts/redirect.mp3/cdn.pri.org/sites/default/files/undiscovered/episode-audio/trailer-final.mp3' }] },
];
